apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
type: Opaque
data:
    mysql-root-password: YXJraHVudA==
    nodejs-env: ZGV2ZWxvcG1lbnQ=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam-mysql
  labels:
    app: mysqldb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysqldb
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - image: "{{ .Values.image.repository }}"
        name: {{ .Values.image.name }}
        ports:
          - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqldb-secret
              key: mysql-root-password

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
